### ISSUE TITLE
How to use this style with openmaptiles stack / tileserver-gl

### ISSUE THREAD

**Issue by hellowtisch** [openmaptiles/klokantech-3d-gl-style#3]
When I try to use this style with the openmaptiles stack, through an edited style.json file, there are numerous errors that the sprites cannot be found under the mapbox:/ URL. 
The same problem occurs after uploading the style to mapnik, adding my mapbox api public key and exporting it afterwards.
Please add documentation on how to get this done.

**Comment by klokan** [comment]
Check gh-pages branch of the style repositories - made with Travis automatically on every push. Especially see the style-local.json.

**Comment by klokan** [comment]
If you need more help - get one hour from us - and we can discuss anything you need to know.
https://openmaptiles.com/support/
