### ISSUE TITLE
Building extrusion not working with tileserver-gl raster tiles

### ISSUE THREAD

**Issue by hellowtisch** [openmaptiles/klokantech-3d-gl-style#4]
Hi, is there a working example for rendering this style as raster-tiles with tileserver-gl?
Everything works fine with vector tiles, however when using raster-tiles, building are not extruded.

**Comment by petrsloup** [comment]
The extrusion is currently not supported in the underlying mapbox-gl-native library. The support was added in 3.6.0 (https://github.com/mapbox/mapbox-gl-native/issues/6745), but it was not yet released for the node platform.
