### ISSUE TITLE
Filter which buildings are extruded

### ISSUE THREAD

**Issue by nicooprat** [openmaptiles/klokantech-3d-gl-style#5]
I'd like to show in 3D only some kind of buildings, the most important ones like historical monuments. I searched the building layer spec but it doesn't look like there's any filter available. Do you think it's possible? Thanks.

**Comment by jirik** [comment]
No, currently it's not possible. You would need to extend OpenMapTiles schema with some new attribute for filtering.

Notice that there are many buildings, so adding attributes to this layer can easily increase tile size a lot.
